name: Generate Checksums

on:
  push:
    paths:
     - 'data/**'
     - '.github/workflows/*.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate checksums
        uses: Solratic/checksum-action@v1
        with:
          pattern: "data/*/*.csv.gz"
          suffix: "checksum"

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
